name: Build

on: [push]

jobs:
  unix-build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake .  
    - name: make
      run: make
    - if: startsWith(matrix.os,'ubuntu')
      name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: PassCoder2-linux-x86
        path: bin/PassCoder2
    - if: startsWith(matrix.os, 'macOS')
      name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: PassCoder2-macos-x86
        path: bin/PassCoder2
  win-build:
    name: Test on windows-latest
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake .  
    - name: make
      run: cmake --build . --target ALL_BUILD --config Release -- /nologo /verbosity:minimal /maxcpucount
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: PassCoder2-windows-x86
        path: bin/Release/PassCoder2.exe